site_name: User guide title
site_url: https://githubusername.github.io/site
theme:
  name: material
nav:
  - Introduction: 'index.md'
  - Food: 'food.md'
  - Blacksburg Entertainment: 'blacksburg_entertainment.md'
  - On-Campus Entertainment: 'on_campus_entertainment.md'
  - Shopping: 'shopping.md'
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg